#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASHRC="${HOME}/.bashrc"
START_MARK="# >>> muav autouavenv >>>"
END_MARK="# <<< muav autouavenv <<<"
OLD_START_MARK="# >>> muav autorosenv >>>"
OLD_END_MARK="# <<< muav autorosenv <<<"
ROS_SETUP="/opt/ros/noetic/setup.bash"
case "${UAV_NAME:-}" in
  uav0|uav1|uav2|uav3|uav4)
    DEFAULT_UAV_NAME="${UAV_NAME}"
    ;;
  *)
    DEFAULT_UAV_NAME="uav"
    ;;
esac

mapfile -t SETUP_FILES < <(find "${SCRIPT_DIR}" -type f -path "*/devel/setup.bash" | sort)

if [ "${#SETUP_FILES[@]}" -eq 0 ]; then
  echo "No devel/setup.bash found under ${SCRIPT_DIR}" >&2
  exit 1
fi

setup_list_file="$(mktemp)"
tmp_file="$(mktemp)"
cleanup() {
  rm -f "${setup_list_file}" "${tmp_file}"
}
trap cleanup EXIT

printf '%s\n' "${SETUP_FILES[@]}" > "${setup_list_file}"

if [ -f "${BASHRC}" ]; then
  python3 - "${BASHRC}" "${setup_list_file}" "${START_MARK}" "${END_MARK}" "${OLD_START_MARK}" "${OLD_END_MARK}" "${ROS_SETUP}" "${SCRIPT_DIR}" > "${tmp_file}" <<'PY'
import re
import shlex
import sys
from pathlib import Path

bashrc_path = Path(sys.argv[1])
setup_list_path = Path(sys.argv[2])
start_mark = sys.argv[3]
end_mark = sys.argv[4]
old_start_mark = sys.argv[5]
old_end_mark = sys.argv[6]
ros_setup = str(Path(sys.argv[7]).resolve())
project_dir = str(Path(sys.argv[8]).resolve())

managed_setups = {str(Path(line.strip()).resolve()) for line in setup_list_path.read_text().splitlines() if line.strip()}
managed_sources = managed_setups | {ros_setup}
source_re = re.compile(r"^\s*(?:\[\s+-f\s+(.+?)\s+\]\s*&&\s*)?(?:source|\.)\s+(.+?)\s*(?:#.*)?$")
old_namespace_var = "ROS" + "_NAMESPACE"
namespace_re = re.compile(r"^\s*(?:export\s+)?(?:UAV_NAME|" + re.escape(old_namespace_var) + r")=.*$")
cd_re = re.compile(r"^\s*cd\s+(.+?)\s*(?:#.*)?$")

skip = False
for raw_line in bashrc_path.read_text().splitlines():
    line = raw_line.rstrip("\n")
    if line in (start_mark, old_start_mark):
        skip = True
        continue
    if line in (end_mark, old_end_mark):
        skip = False
        continue
    if skip:
        continue

    match = source_re.match(line)
    if match:
        source_token = match.group(2).strip()
        try:
            parts = shlex.split(source_token)
        except ValueError:
            parts = []
        if len(parts) == 1:
            source_path = Path(parts[0]).expanduser()
            if not source_path.is_absolute():
                source_path = (Path.home() / source_path).resolve()
            else:
                source_path = source_path.resolve()
            if str(source_path) in managed_sources:
                continue

    if namespace_re.match(line):
        continue

    cd_match = cd_re.match(line)
    if cd_match:
        cd_token = cd_match.group(1).strip()
        try:
            parts = shlex.split(cd_token)
        except ValueError:
            parts = []
        if len(parts) == 1:
            cd_path = Path(parts[0]).expanduser()
            if not cd_path.is_absolute():
                cd_path = (Path.home() / cd_path).resolve()
            else:
                cd_path = cd_path.resolve()
            if str(cd_path) == project_dir:
                continue

    print(line)
PY
else
  : > "${tmp_file}"
fi

{
  printf '\n%s\n' "${START_MARK}"
  printf '# Generated by %s\n' "${SCRIPT_DIR}/autouavenv.sh"
  printf '[ -f %q ] && source %q\n' "${ROS_SETUP}" "${ROS_SETUP}"
  printf 'export UAV_NAME=%q\n' "${DEFAULT_UAV_NAME}"
  printf 'cd %q\n' "${SCRIPT_DIR}"
  for setup_file in "${SETUP_FILES[@]}"; do
    printf '[ -f %q ] && source %q\n' "${setup_file}" "${setup_file}"
  done
  printf '%s\n' "${END_MARK}"
} >> "${tmp_file}"

cp "${tmp_file}" "${BASHRC}"

echo "Updated ${BASHRC} with:"
for setup_file in "${SETUP_FILES[@]}"; do
  echo "  ${setup_file}"
done

set +e +u
source "${BASHRC}"
source_status=$?
set -euo pipefail

if [ "${source_status}" -ne 0 ]; then
  echo "Warning: source ${BASHRC} returned ${source_status}; open a new terminal or run: source ${BASHRC}" >&2
fi

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  echo "For this terminal to inherit the environment immediately, run: source ${SCRIPT_DIR}/autouavenv.sh"
else
  for setup_file in "${SETUP_FILES[@]}"; do
    source "${setup_file}"
  done
fi
