%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2


imu_topic: "mavros/imu/data_raw"
image0_topic: "camera/infra1/image_rect_raw"
image1_topic: "camera/infra2/image_rect_raw"




output_path: "/home/uav/Desktop/uav_project/muav/core/vins_output"


cam0_calib: "left.yaml"
cam1_calib: "right.yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

# online
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -2.1792499154815737e-03, -1.9012189238187427e-02,
       9.9981687699807187e-01, 2.3460848181173172e-01,
       -9.9999688249343355e-01, -1.1773141828781419e-03,
       -2.2020296839793674e-03, -1.7820079802113198e-02,
       1.2189639946306174e-03, -9.9981855883539517e-01,
       -1.9009564305729310e-02, 3.3859462838956099e-02, 0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -7.2738768496369843e-03, -2.3355546013193285e-02,
       9.9970075982065865e-01, 2.1976104851172049e-01,
       -9.9997317236156946e-01, -6.9318932714135251e-04,
       -7.2920535993515334e-03, -6.9064874709730356e-02,
       8.6329179041294557e-04, -9.9972698170999807e-01,
       -2.3349877265250729e-02, 3.7421089901407092e-02, 0., 0., 0., 1. ]

# # offline_param
# body_T_cam0: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [0.03379381, 0.05601212, 
#             0.99785802, 0.00128844, 
#             -0.99896458, 0.03232157, 
#             0.03201699, -0.00405034, 
#             -0.030459, -0.99790679, 
#             0.0570464, 0.00908112, 0., 0., 0., 1.]
# body_T_cam1: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [0.02889302, 0.05381805, 
#             0.99813266, 0.00404231, 
#             -0.99914426, 0.03112077, 
#             0.02724431, -0.05578878, 
#             -0.02959642, -0.99806569, 
#             0.05467117, 0.00558867, 0., 0., 0., 1.]
            
#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805         # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: -0.025                           # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/fast/savedfiles/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
